<a href="https://colab.research.google.com/github/mohinilodhi/data---analysis-projects/blob/main/merge_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Department": ["IT", "HR", "Finance", "IT"]
})

df2 = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Salary": [50000, 60000, 70000, 55000]
})



df = pd.merge(df1, df2, on="Name")
print(df)

  Name Department  Salary
0    A         IT   50000
1    B         HR   60000
2    C    Finance   70000
3    D         IT   55000

In [7]:
result = df.groupby("Department")["Salary"].max()
print(result)

Department
Finance    70000
HR         60000
IT         55000
Name: Salary, dtype: int64

In [8]:
result = df.loc[df.groupby("Department")["Salary"].idxmax()]
print(result)

  Name Department  Salary
2    C    Finance   70000
1    B         HR   60000
3    D         IT   55000

In [9]:
df["Sales"] = [200000, 150000, 300000, 250000]

In [10]:
df["Efficiency"] = df["Sales"] / df["Salary"]
print(df)

  Name Department  Salary   Sales  Efficiency
0    A         IT   50000  200000    4.000000
1    B         HR   60000  150000    2.500000
2    C    Finance   70000  300000    4.285714
3    D         IT   55000  250000    4.545455

In [11]:
df["Efficiency"]

0    4.000000
1    2.500000
2    4.285714
3    4.545455
Name: Efficiency, dtype: float64

In [12]:
result = df.groupby("Department")["Efficiency"].mean()
print(result)

Department
Finance    4.285714
HR         2.500000
IT         4.272727
Name: Efficiency, dtype: float64

In [13]:
best = df.loc[df["Efficiency"].idxmax()]
print(best)

Name                 D
Department          IT
Salary           55000
Sales           250000
Efficiency    4.545455
Name: 3, dtype: object

In [14]:
bad = df.loc[df["Efficiency"].idxmin()]
print(bad)

Name               B
Department        HR
Salary         60000
Sales         150000
Efficiency       2.5
Name: 1, dtype: object

In [15]:
df.loc[df.groupby("Department")["Efficiency"].idxmin()]

  Name Department  Salary   Sales  Efficiency
2    C    Finance   70000  300000    4.285714
1    B         HR   60000  150000    2.500000
0    A         IT   50000  200000    4.000000

In [16]:
df.loc[df.groupby("Department")["Efficiency"].idxmax()]

  Name Department  Salary   Sales  Efficiency
2    C    Finance   70000  300000    4.285714
1    B         HR   60000  150000    2.500000
3    D         IT   55000  250000    4.545455

In [17]:
df["Efficiency"] = [0,5,28,54]

In [18]:
df["Performance"] = df["Efficiency"].apply(
    lambda x: "High" if x > 5 else ("Medium" if x >= 3 else "Low")
)

print(df[["Name", "Efficiency", "Performance"]])

  Name  Efficiency Performance
0    A           0         Low
1    B           5      Medium
2    C          28        High
3    D          54        High