<a href="https://colab.research.google.com/github/mohinilodhi/data---analysis-projects/blob/main/miniDataset06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D"],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Salary": [50000, 60000, 70000, 55000],
    "Sales": [200, 150, 300, 250]
}

df = pd.DataFrame(data)
print(df)

  Name Department  Salary  Sales
0    A         IT   50000    200
1    B         HR   60000    150
2    C    Finance   70000    300
3    D         IT   55000    250

filtering

In [70]:
df.isnull()

    Name  Department  Salary  Sales
0  False       False   False  False
1  False       False   False  False
2  False       False   False  False
3  False       False   False  False

In [71]:
df.dropna()

  Name Department  Salary  Sales
0    A         IT   50000    200
1    B         HR   60000    150
2    C    Finance   70000    300
3    D         IT   55000    250

In [72]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [73]:
df.drop_duplicates()

  Name Department  Salary  Sales
0    A         IT   50000    200
1    B         HR   60000    150
2    C    Finance   70000    300
3    D         IT   55000    250

groupby things

In [74]:
df["Salary"].min()

50000

In [75]:
df["Salary"].max()

70000

In [76]:
df["Salary"].mean()

np.float64(58750.0)

In [77]:
df["Salary"].sum()

np.int64(235000)

In [78]:
df.pivot_table(values="Salary",index="Department",aggfunc ="mean")

             Salary
Department
Finance     70000.0
HR          60000.0
IT          52500.0

In [79]:
df.pivot_table(values="Salary", index="Department", aggfunc="sum")

            Salary
Department
Finance      70000
HR           60000
IT          105000

In [80]:
df.pivot_table(values="Salary", index="Department", aggfunc=["max","mean","min"])

              max     mean    min
           Salary   Salary Salary
Department
Finance     70000  70000.0  70000
HR          60000  60000.0  60000
IT          55000  52500.0  50000

In [81]:
df.pivot_table(values=["Salary","Sales"], index="Department",aggfunc="mean")

             Salary  Sales
Department
Finance     70000.0  300.0
HR          60000.0  150.0
IT          52500.0  225.0

In [82]:
df.pivot_table(
    values="Salary",
    index="Department",
    columns="Name",
    aggfunc="sum",
    fill_value=0
)

Name            A      B      C      D
Department
Finance         0      0  70000      0
HR              0  60000      0      0
IT          50000      0      0  55000

In [83]:
df["Salary"] = df["Salary"].apply(lambda x: x *2)
print(df)

  Name Department  Salary  Sales
0    A         IT  100000    200
1    B         HR  120000    150
2    C    Finance  140000    300
3    D         IT  110000    250

In [84]:
df["Sales"] = df["Sales"].apply(lambda x: x *4)
print(df)

  Name Department  Salary  Sales
0    A         IT  100000    800
1    B         HR  120000    600
2    C    Finance  140000   1200
3    D         IT  110000   1000

In [85]:
df["Status"] = df["Sales"].apply(
    lambda x: "Good" if x> 100 else "average"
)
print(df)

  Name Department  Salary  Sales Status
0    A         IT  100000    800   Good
1    B         HR  120000    600   Good
2    C    Finance  140000   1200   Good
3    D         IT  110000   1000   Good

apply with multiple columns

In [86]:
df["Bonus"] = df.apply(
    lambda row:
    row["Salary"] * 0.20 if row["Sales"] > 200
    else row["Salary"] * 0.10,
    axis=1
)
print(df)

  Name Department  Salary  Sales Status    Bonus
0    A         IT  100000    800   Good  20000.0
1    B         HR  120000    600   Good  24000.0
2    C    Finance  140000   1200   Good  28000.0
3    D         IT  110000   1000   Good  22000.0

In [87]:
df["Efficiency"] = df["Sales"] / df["Salary"]
print(df)

  Name Department  Salary  Sales Status    Bonus  Efficiency
0    A         IT  100000    800   Good  20000.0    0.008000
1    B         HR  120000    600   Good  24000.0    0.005000
2    C    Finance  140000   1200   Good  28000.0    0.008571
3    D         IT  110000   1000   Good  22000.0    0.009091

In [88]:
best = df.loc[df["Efficiency"].idxmax()]
print(best)

Name                 D
Department          IT
Salary          110000
Sales             1000
Status            Good
Bonus          22000.0
Efficiency    0.009091
Name: 3, dtype: object

In [89]:
bad = df.loc[df["Efficiency"].idxmin()]
print(bad)

Name                B
Department         HR
Salary         120000
Sales             600
Status           Good
Bonus         24000.0
Efficiency      0.005
Name: 1, dtype: object